name: Build x86 Amperage
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Build
        run: dotnet publish AmperageKit.sln -c Release --self-contained=false -o output
      - name: Upload Workloads
        # 这里可增加从微软下载或手动上传 assets
      - name: Package
        run: Compress-Archive -Path output\* -DestinationPath Amperage_x86.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: amperage-x86
          path: Amperage_x86.zip
