name: Build x86 AmperageKit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore AmperageKit.sln

      - name: Build (win10-x64)
        run: dotnet publish AmperageKit.sln -c Release  --self-contained false -o output

      - name: Show output
        run: dir output

      - name: Create ZIP archive
        run: Compress-Archive -Path output\* -DestinationPath Amperage_x86.zip

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: amperage-x86
          path: Amperage_x86.zip
